2019-07-16 14:38:40,644 - WARNING -  * Debugger is active!
2019-07-16 14:38:40,648 - INFO -  * Debugger PIN: 134-442-503
2019-07-16 14:38:45,658 - DEBUG - ('SELECT `t1`.`customerID`, `t1`.`name`, `t1`.`address`, `t1`.`phone` FROM `customer` AS `t1` WHERE (`t1`.`name` = %s) LIMIT %s OFFSET %s', ['FizzBuzz Inc', 1, 0])
2019-07-16 14:38:45,663 - DEBUG - New Customer Hit:. Name Integrity Passed
2019-07-16 14:38:45,663 - DEBUG - ('INSERT INTO `customer` (`name`, `address`, `phone`) VALUES (%s, %s, %s)', ['FizzBuzz Inc', '1523 Holiday Drive', '314-159-2653'])
2019-07-16 14:38:45,666 - INFO - New Customer Hit: Success. New Customer Has Been Created. Name: FizzBuzz Inc
2019-07-16 14:38:45,666 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/newCustomer HTTP/1.1" 200 -
2019-07-16 14:38:45,671 - INFO - New Customer Hit: No Name Provided
2019-07-16 14:38:45,671 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/newCustomer HTTP/1.1" 400 -
2019-07-16 14:38:45,674 - INFO - New Customer Hit: No Address Provided
2019-07-16 14:38:45,675 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/newCustomer HTTP/1.1" 400 -
2019-07-16 14:38:45,679 - INFO - New Customer Hit: No Phone Provided
2019-07-16 14:38:45,680 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/newCustomer HTTP/1.1" 400 -
2019-07-16 14:38:45,684 - DEBUG - ('SELECT `t1`.`customerID`, `t1`.`name`, `t1`.`address`, `t1`.`phone` FROM `customer` AS `t1` WHERE (`t1`.`name` = %s) LIMIT %s OFFSET %s', ['FizzBuzz Inc', 1, 0])
2019-07-16 14:38:45,688 - INFO - New Customer Hit: Name Integrity Failed
2019-07-16 14:38:45,689 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/newCustomer HTTP/1.1" 400 -
2019-07-16 14:38:45,693 - DEBUG - ('SELECT `t1`.`customerID`, `t1`.`name`, `t1`.`address`, `t1`.`phone` FROM `customer` AS `t1` WHERE (`t1`.`customerID` = %s) LIMIT %s OFFSET %s', [1, 1, 0])
2019-07-16 14:38:45,697 - DEBUG - Get Customer Hit: Get Customer Info Request Completed. CID: 1
2019-07-16 14:38:45,698 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/getCustomer HTTP/1.1" 200 -
2019-07-16 14:38:45,702 - INFO - Get Customer Hit: No CID Provided
2019-07-16 14:38:45,702 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /customer/getCustomer HTTP/1.1" 200 -
2019-07-16 14:38:45,707 - DEBUG - ('INSERT INTO `device` (`name`, `location`, `latitude`, `longitude`, `customerOwner_id`, `dataControllerPeriod`, `commandControllerPeriod`, `missedCommands`, `commandTimeWindow`, `status`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)', ["Brendon's MEGA Machine", 'Planet Drron', None, None, 1, 5.0, 5.0, 0, datetime.datetime(2019, 7, 16, 20, 38, 50, 706797), 0])
2019-07-16 14:38:45,712 - INFO - New Device Hit: Success. New Device Has Been Created. Name: Brendon's MEGA Machine
2019-07-16 14:38:45,712 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/newDevice HTTP/1.1" 200 -
2019-07-16 14:38:45,716 - INFO - New Device Hit: No Name Provided
2019-07-16 14:38:45,716 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/newDevice HTTP/1.1" 400 -
2019-07-16 14:38:45,720 - INFO - New Device Hit: No Location Provided
2019-07-16 14:38:45,721 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/newDevice HTTP/1.1" 400 -
2019-07-16 14:38:45,725 - INFO - New Device Hit: No Customer Owner Provided
2019-07-16 14:38:45,725 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/newDevice HTTP/1.1" 400 -
2019-07-16 14:38:45,729 - DEBUG - ('INSERT INTO `device` (`name`, `location`, `latitude`, `longitude`, `customerOwner_id`, `dataControllerPeriod`, `commandControllerPeriod`, `missedCommands`, `commandTimeWindow`, `status`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)', ["Brendon's MEGA Machine", 'Planet Drron', None, None, 1234567890, 5.0, 5.0, 0, datetime.datetime(2019, 7, 16, 20, 38, 50, 729658), 0])
2019-07-16 14:38:45,735 - WARNING - Error In Device Creation.
Exception: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`IoT`.`device`, CONSTRAINT `device_ibfk_1` FOREIGN KEY (`customerOwner_id`) REFERENCES `customer` (`customerID`))')
TraceBack: Traceback (most recent call last):
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`IoT`.`device`, CONSTRAINT `device_ibfk_1` FOREIGN KEY (`customerOwner_id`) REFERENCES `customer` (`customerID`))')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brendonstanley/repos/totality/Back_End/creationAPI/creationServerApp.py", line 118, in newDevice
    commandControllerPeriod=commandControllerPeriod, commandTimeWindow=commandTimeWindow, customerOwner=customerOwner)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 6012, in create
    inst.save(force_insert=True)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 6201, in save
    pk = self.insert(**field_dict).execute()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 1856, in execute
    return self._execute(database)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2572, in _execute
    return super(Insert, self)._execute(database)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2320, in _execute
    cursor = database.execute(self)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2962, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2956, in execute_sql
    self.commit()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
peewee.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`IoT`.`device`, CONSTRAINT `device_ibfk_1` FOREIGN KEY (`customerOwner_id`) REFERENCES `customer` (`customerID`))')

2019-07-16 14:38:45,735 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/newDevice HTTP/1.1" 400 -
2019-07-16 14:38:45,740 - DEBUG - ('SELECT `t1`.`deviceID`, `t1`.`name`, `t1`.`location`, `t1`.`latitude`, `t1`.`longitude`, `t1`.`customerOwner_id`, `t1`.`dataControllerPeriod`, `t1`.`commandControllerPeriod`, `t1`.`timeOfLastCheckIn`, `t1`.`missedCommands`, `t1`.`commandTimeWindow`, `t1`.`status` FROM `device` AS `t1` WHERE (`t1`.`deviceID` = %s) LIMIT %s OFFSET %s', [1, 1, 0])
2019-07-16 14:38:45,744 - DEBUG - ('SELECT `t1`.`customerID`, `t1`.`name`, `t1`.`address`, `t1`.`phone` FROM `customer` AS `t1` WHERE (`t1`.`customerID` = %s) LIMIT %s OFFSET %s', [1, 1, 0])
2019-07-16 14:38:45,746 - DEBUG - Get Device Info Hit: Get Device Info Request Completed. DID: 1
2019-07-16 14:38:45,746 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/getDeviceInfo HTTP/1.1" 200 -
2019-07-16 14:38:45,750 - INFO - Get Device Info Hit: No DID Provided
2019-07-16 14:38:45,750 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/getDeviceInfo HTTP/1.1" 400 -
2019-07-16 14:38:45,756 - DEBUG - ('SELECT `t1`.`deviceID`, `t1`.`name`, `t1`.`location`, `t1`.`latitude`, `t1`.`longitude`, `t1`.`customerOwner_id`, `t1`.`dataControllerPeriod`, `t1`.`commandControllerPeriod`, `t1`.`timeOfLastCheckIn`, `t1`.`missedCommands`, `t1`.`commandTimeWindow`, `t1`.`status` FROM `device` AS `t1` WHERE (`t1`.`deviceID` = %s) LIMIT %s OFFSET %s', [1234567890, 1, 0])
2019-07-16 14:38:45,760 - WARNING - Get Device Info Hit: Unable To Get Customer Info. DID: 1234567890
Exception: <Model: Device> instance matching query does not exist:
SQL: SELECT `t1`.`deviceID`, `t1`.`name`, `t1`.`location`, `t1`.`latitude`, `t1`.`longitude`, `t1`.`customerOwner_id`, `t1`.`dataControllerPeriod`, `t1`.`commandControllerPeriod`, `t1`.`timeOfLastCheckIn`, `t1`.`missedCommands`, `t1`.`commandTimeWindow`, `t1`.`status` FROM `device` AS `t1` WHERE (`t1`.`deviceID` = %s) LIMIT %s OFFSET %s
Params: [1234567890, 1, 0]
TraceBack: Traceback (most recent call last):
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 6496, in get
    return clone.execute(database)[0]
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 4024, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brendonstanley/repos/totality/Back_End/creationAPI/creationServerApp.py", line 154, in getDeviceInfo
    device = Device.get(Device.deviceID == DID)
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 6091, in get
    return sq.get()
  File "/Users/brendonstanley/virtual/Totality/lib/python3.7/site-packages/peewee.py", line 6501, in get
    (clone.model, sql, params))
Back_End.creationAPI.models.DeviceDoesNotExist: <Model: Device> instance matching query does not exist:
SQL: SELECT `t1`.`deviceID`, `t1`.`name`, `t1`.`location`, `t1`.`latitude`, `t1`.`longitude`, `t1`.`customerOwner_id`, `t1`.`dataControllerPeriod`, `t1`.`commandControllerPeriod`, `t1`.`timeOfLastCheckIn`, `t1`.`missedCommands`, `t1`.`commandTimeWindow`, `t1`.`status` FROM `device` AS `t1` WHERE (`t1`.`deviceID` = %s) LIMIT %s OFFSET %s
Params: [1234567890, 1, 0]

2019-07-16 14:38:45,761 - INFO - 127.0.0.1 - - [16/Jul/2019 14:38:45] "POST /device/getDeviceInfo HTTP/1.1" 400 -
